name: reviewdog
on: [pull_request]
jobs:
  vint:
    name: runner / vint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - name: vint
        uses: ./
        with:
          github_token: ${{ secrets.github_token }}
      - name: vint-check
        uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          level: warning
      - name: vint-pr-review
        uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
